/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as AdminMemoryRouteImport } from './routes/admin.memory'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminInterviewsRouteImport } from './routes/admin.interviews'
import { Route as AdminConflictsRouteImport } from './routes/admin.conflicts'
import { Route as AdminInterviewsIndexRouteImport } from './routes/admin.interviews.index'
import { Route as AdminInterviewsIdRouteImport } from './routes/admin.interviews.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterviewsRoute = AdminInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConflictsRoute = AdminConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterviewsIndexRoute = AdminInterviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminInterviewsRoute,
} as any)
const AdminInterviewsIdRoute = AdminInterviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInterviewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/admin/conflicts': typeof AdminConflictsRoute
  '/admin/interviews': typeof AdminInterviewsRouteWithChildren
  '/admin/map': typeof AdminMapRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/interview/$id': typeof InterviewIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/interviews/$id': typeof AdminInterviewsIdRoute
  '/admin/interviews/': typeof AdminInterviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/admin/conflicts': typeof AdminConflictsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/interview/$id': typeof InterviewIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/interviews/$id': typeof AdminInterviewsIdRoute
  '/admin/interviews': typeof AdminInterviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/admin/conflicts': typeof AdminConflictsRoute
  '/admin/interviews': typeof AdminInterviewsRouteWithChildren
  '/admin/map': typeof AdminMapRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/interview/$id': typeof InterviewIdRoute
  '/quiz/$id': typeof QuizIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/interviews/$id': typeof AdminInterviewsIdRoute
  '/admin/interviews/': typeof AdminInterviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/settings'
    | '/admin/conflicts'
    | '/admin/interviews'
    | '/admin/map'
    | '/admin/memory'
    | '/interview/$id'
    | '/quiz/$id'
    | '/admin/'
    | '/admin/interviews/$id'
    | '/admin/interviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/settings'
    | '/admin/conflicts'
    | '/admin/map'
    | '/admin/memory'
    | '/interview/$id'
    | '/quiz/$id'
    | '/admin'
    | '/admin/interviews/$id'
    | '/admin/interviews'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/history'
    | '/settings'
    | '/admin/conflicts'
    | '/admin/interviews'
    | '/admin/map'
    | '/admin/memory'
    | '/interview/$id'
    | '/quiz/$id'
    | '/admin/'
    | '/admin/interviews/$id'
    | '/admin/interviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  InterviewIdRoute: typeof InterviewIdRoute
  QuizIdRoute: typeof QuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interviews': {
      id: '/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminInterviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conflicts': {
      id: '/admin/conflicts'
      path: '/conflicts'
      fullPath: '/admin/conflicts'
      preLoaderRoute: typeof AdminConflictsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interviews/': {
      id: '/admin/interviews/'
      path: '/'
      fullPath: '/admin/interviews/'
      preLoaderRoute: typeof AdminInterviewsIndexRouteImport
      parentRoute: typeof AdminInterviewsRoute
    }
    '/admin/interviews/$id': {
      id: '/admin/interviews/$id'
      path: '/$id'
      fullPath: '/admin/interviews/$id'
      preLoaderRoute: typeof AdminInterviewsIdRouteImport
      parentRoute: typeof AdminInterviewsRoute
    }
  }
}

interface AdminInterviewsRouteChildren {
  AdminInterviewsIdRoute: typeof AdminInterviewsIdRoute
  AdminInterviewsIndexRoute: typeof AdminInterviewsIndexRoute
}

const AdminInterviewsRouteChildren: AdminInterviewsRouteChildren = {
  AdminInterviewsIdRoute: AdminInterviewsIdRoute,
  AdminInterviewsIndexRoute: AdminInterviewsIndexRoute,
}

const AdminInterviewsRouteWithChildren = AdminInterviewsRoute._addFileChildren(
  AdminInterviewsRouteChildren,
)

interface AdminRouteChildren {
  AdminConflictsRoute: typeof AdminConflictsRoute
  AdminInterviewsRoute: typeof AdminInterviewsRouteWithChildren
  AdminMapRoute: typeof AdminMapRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConflictsRoute: AdminConflictsRoute,
  AdminInterviewsRoute: AdminInterviewsRouteWithChildren,
  AdminMapRoute: AdminMapRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  InterviewIdRoute: InterviewIdRoute,
  QuizIdRoute: QuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
